### ISSUE TITLE
Massive 404s

### ISSUE THREAD

**Issue by xocasdashdash** [johannesss/vuejs-spotify-playlist#2]
Hi, 
I just tried to test it and I'm getting massive 404s from spotify's api.
What can i send you to help debug the problem?

**Comment by johannesss** [comment]
Hello! I noticed that as well while coding.
I had another look at the issue and found that the playlist id's that 404 are playlists that I follow but were created by another user and are marked private. I will have a look at this when I get off work. We need to filter the playlists by user before proceeding to look up the artists.

Thanks for your interest!

**Comment by johannesss** [comment]
Problem solved
